USE [master]
GO

/****** Object:  Database [CRUDFromExcel]    Script Date: 7/8/2019 11:50:56 AM ******/
CREATE DATABASE [CRUDFromExcel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CRUDFromExcel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CRUDFromExcel.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CRUDFromExcel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CRUDFromExcel_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CRUDFromExcel] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CRUDFromExcel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CRUDFromExcel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET ARITHABORT OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CRUDFromExcel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CRUDFromExcel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CRUDFromExcel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CRUDFromExcel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET RECOVERY FULL 
GO

ALTER DATABASE [CRUDFromExcel] SET  MULTI_USER 
GO

ALTER DATABASE [CRUDFromExcel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CRUDFromExcel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CRUDFromExcel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CRUDFromExcel] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CRUDFromExcel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CRUDFromExcel] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CRUDFromExcel] SET  READ_WRITE 
GO
